Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
License key 'DEF456' used by IP address 127.0.0.1
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
License key 'DEF456' used by IP address 127.0.0.1
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
License key 'DEF456' used by IP address 127.0.0.1
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
License key 'DEF456' used by IP address 127.0.0.1
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /license_key_list.html
Not Found: /favicon.ico
Not Found: /license_keys
Not Found: /license_keys/
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Not Found: /favicon.ico
Watching for file changes with StatReloader
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Not Found: /favicon.ico
Internal Server Error: /license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 134, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 131, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader_tags.py", line 109, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/engine.py", line 163, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 96, in license_key_list
    return render(request, 'license_manager/license_key_list.html', {'license_keys': license_keys})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
Not Found: /favicon.ico
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing.): /license-keys/
Forbidden (CSRF token missing.): /license-keys/
Not Found: /favicon.ico
Not Found: /favicon.ico
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing.): /create-license-key/
Not Found: /favicon.ico
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myproject/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myproject/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /delete-license-key/undefined/
/home/syedyasin/Desktop/demo_script/myapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /delete-license-key/undefined/
Not Found: /delete-license-key/undefined/
Not Found: /delete-license-key/undefined/
Not Found: /delete-license-key/undefined/
Not Found: /delete-license-key/undefined/
Not Found: /delete-license-key/undefined/
Not Found: /delete-license-key/undefined/
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /get-license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 266, in get_license_keys
    Q(name__icontains=search_term) | Q(key__icontains=search_term)
    ^
NameError: name 'Q' is not defined
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /get-license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 267, in get_license_keys
    Q(name__icontains=search_term) | Q(key__icontains=search_term)
    ^
NameError: name 'Q' is not defined
Internal Server Error: /get-license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 267, in get_license_keys
    Q(name__icontains=search_term) | Q(key__icontains=search_term)
    ^
NameError: name 'Q' is not defined
Internal Server Error: /get-license-keys/
Traceback (most recent call last):
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/venv/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/syedyasin/Desktop/demo_script/myapp/views.py", line 267, in get_license_keys
    Q(name__icontains=search_term) | Q(key__icontains=search_term)
    ^
NameError: name 'Q' is not defined
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/syedyasin/Desktop/demo_script/myapp/views.py changed, reloading.
Watching for file changes with StatReloader
License key 'howareyou' used by IP address 127.0.0.1
License key 'howareyou' used by IP address 127.0.0.1
/home/syedyasin/Desktop/demo_script/myproject/settings.py changed, reloading.
